### ISSUE TITLE
Set up SSL certs for website and package repo

### ISSUE THREAD

**Issue by q5sys** [project-trident/trident-website#14]
The thing must be done.

**Comment by jdrch** [comment]
Just gonna chime in that this is imperative. I totally acknowledge that this is a volunteer effort, Trident is free, and the dev team have done a great job so far, but this is a serious issue that flies in the face of what BSD (typically) stands for: doing things The Right Way (TM) and security.

**Comment by beanpole135** [comment]
The package server now has an auto-renewed letsencrypt certificate for https access, and http usage is automatically redirected to https.
The website itself is still using http only at the moment, and I have WIP to move that one over as well, but since it is purely a static html landing page with no info/access to any file that one is not quite as high on the priority list.

**Comment by jdrch** [comment]
@beanpole135 Thanks so much :) I feel better recommending people try Trident now.
